services:
  backend:
    image: "cronback-backend:latest"
    restart: unless-stopped
    volumes:
      - cronback_data:/data
    env_file:
      - ../.env
    command:
      - '--log-format'
      - 'json'
  openapi:
    image: "cronback-openapi:latest"
    restart: unless-stopped
volumes:
  cronback_data:
