[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
proto = { path = "../proto" }
rand = "0.8.5"
chrono = "0.4"
serde = "1"
thiserror = "1"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
colored = "2.0"
tracing = { version = "0.1", features = ["log"] }
tonic = "0.8"
prost = "0.11"
metrics = "0.20"
tower = { version = "0.4", features = ["full"] }
tonic-reflection = "0.6"
cron = "0.12"
chrono-tz = "0.8"
tokio-stream = { version = "0.1", features = ["net"] }
tempfile = "3.4"
prost-types = "0.11"
