[package]
name = "dispatcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
uuid = { version = "1.2.2", features = ["v4"] }
chrono = "0.4"
serde = "1"
thiserror = "1"
anyhow = "1.0.69"
tokio = { version = "1", features = ["full"] }
colored = "2.0"
tracing = { version = "0.1", features = ["log"] }
