//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use chrono::{DateTime, Utc};
use lib::prelude::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub key_id: String,
    pub hash: String,
    pub hash_version: String,
    pub project_id: ValidShardedId<ProjectId>,
    pub name: String,
    pub created_at: DateTime<Utc>,
    pub metadata: Metadata,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult,
)]
pub struct Metadata {
    pub creator_user_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
