[package]
name = "cronback-client"
description = """\
  A client library for https://cronback.me service. \
  Cronback provides developers a reliable and flexible solution to schedule \
  one-time, recurring cron, and on-demand webhooks.
  """
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
categories = ["network-programming", "api-bindings"]
keywords = ["cron", "webhooks", "scheduler", "job", "periodic"]
repository = "https://github.com/devtari-io/cronback"
homepage = "https://cronback.me"

[package.metadata.workspaces]
# We maintain version independently from the workspace.
independent = true

[features]
default = []
admin = ["cronback-api-model/admin"]
# We maintain the CLI and rust-client versions independently from the workspace.
[dependencies]
# Internal dependencies
cronback-api-model = { workspace = true, features = ["client"] }

reqwest = { workspace = true, features = ["json"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
once_cell = { workspace = true }
http = "0.2.9"
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
monostate = { workspace = true }
serde_with = { version = "3.0.0" }
