[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[lib]
name = "proto"
path = "lib.rs"

[dependencies]
tonic = "0.8"
prost = "0.11"
prost-types = "0.11"

[build-dependencies]
tonic-build = "0.8"
