[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
name = "proto"
path = "lib.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
