[main]
roles = ["api", "dispatcher", "scheduler"]
prometheus_address = "127.0.0.1"
prometheus_port = 9000

[api]
# Localhost only by default
address = "0.0.0.0"
port = 8888

[dispatcher]
# Localhost only by default
address = "0.0.0.0"
port = 9999

[scheduler]
# Localhost only by default
address = "0.0.0.0"
port = 9811
