[main]
roles = ["api", "dispatcher", "scheduler"]
prometheus_address = "127.0.0.1"
prometheus_port = 9000

[api]
# Localhost only by default
address = "0.0.0.0"
port = 8888

[dispatcher]
# Localhost only by default
address = "0.0.0.0"
port = 9999
request_processing_timeout_s = 30

[scheduler]
cell_id = 0
# Localhost only by default
address = "0.0.0.0"
port = 9811
request_processing_timeout_s = 30
spinner_yield_max_ms = 250
max_triggers_per_tick = 100000
dispatcher_uri = "http://127.0.0.1:9999"
