//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::triggers::{Action, Payload};
use crate::model::ValidShardedId;
use crate::types::{ProjectId, RunId, TriggerId};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "runs"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    Serialize,
    Deserialize,
    DeriveActiveModel,
    Eq,
)]
pub struct Model {
    pub id: RunId,
    pub trigger: TriggerId,
    pub project: ValidShardedId<ProjectId>,
    pub created_at: DateTime<Utc>,
    pub payload: Option<Payload>,
    pub action: Action,
    pub status: RunStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Trigger,
    Project,
    CreatedAt,
    Payload,
    Action,
    Status,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
    Project,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);

    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;

    fn def(&self) -> ColumnDef {
        match self {
            | Self::Id => ColumnType::String(None).def(),
            | Self::Trigger => ColumnType::String(None).def(),
            | Self::Project => ColumnType::String(None).def(),
            | Self::CreatedAt => ColumnType::String(None).def(),
            | Self::Payload => ColumnType::String(None).def().null(),
            | Self::Action => ColumnType::String(None).def(),
            | Self::Status => ColumnType::String(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "String(None)")]
pub enum RunStatus {
    #[sea_orm(string_value = "Attempting")]
    Attempting,
    #[sea_orm(string_value = "Succeeded")]
    Succeeded,
    #[sea_orm(string_value = "Failed")]
    Failed,
}
