//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use chrono_tz::Tz;
use monostate::MustBe;
use sea_orm::entity::prelude::*;
use sea_orm::{DeriveActiveEnum, EnumIter, FromJsonQueryResult};
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, skip_serializing_none};

use crate::model::ValidShardedId;
use crate::timeutil::iso8601_dateformat_vec_serde;
use crate::types::{ProjectId, TriggerId, Webhook};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "triggers"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: TriggerId,
    pub project: ValidShardedId<ProjectId>,
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
    pub reference: Option<String>,
    pub payload: Option<Payload>,
    pub schedule: Option<Schedule>,
    pub action: Action,
    pub status: Status,
    pub last_ran_at: Option<DateTime<Utc>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Project,
    Name,
    Description,
    CreatedAt,
    UpdatedAt,
    Reference,
    Payload,
    Schedule,
    Action,
    Status,
    LastRanAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
    Project,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);

    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;

    fn def(&self) -> ColumnDef {
        match self {
            | Self::Id => ColumnType::String(None).def(),
            | Self::Project => ColumnType::String(None).def(),
            | Self::Name => ColumnType::String(None).def().null(),
            | Self::Description => ColumnType::String(None).def().null(),
            | Self::CreatedAt => ColumnType::String(None).def(),
            | Self::UpdatedAt => ColumnType::String(None).def(),
            | Self::Reference => ColumnType::String(None).def().null(),
            | Self::Payload => ColumnType::String(None).def().null(),
            | Self::Schedule => ColumnType::String(None).def().null(),
            | Self::Action => ColumnType::String(None).def().null(),
            | Self::Status => ColumnType::String(None).def(),
            | Self::LastRanAt => ColumnType::String(None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn alive(&self) -> bool {
        self.status.alive()
    }

    pub fn into_manifest(self) -> TriggerManifest {
        TriggerManifest {
            id: self.id,
            project: self.project,
            name: self.name,
            description: self.description,
            created_at: self.created_at,
            updated_at: self.updated_at,
            action: self.action,
            reference: self.reference,
            schedule: self.schedule,
            status: self.status,
            last_ran_at: self.last_ran_at,
        }
    }

    pub fn get_manifest(&self) -> TriggerManifest {
        TriggerManifest {
            id: self.id.clone(),
            project: self.project.clone(),
            name: self.name.clone(),
            description: self.description.clone(),
            created_at: self.created_at,
            updated_at: self.updated_at,
            action: self.action.clone(),
            reference: self.reference.clone(),
            schedule: self.schedule.clone(),
            status: self.status.clone(),
            last_ran_at: self.last_ran_at,
        }
    }

    pub fn update(
        &mut self,
        new_name: String,
        new_description: Option<String>,
        new_reference: Option<String>,
        new_payload: Option<Payload>,
        new_schedule: Option<Schedule>,
        new_action: Action,
    ) {
        self.updated_at = Some(Utc::now());

        self.name = new_name;
        self.description = new_description;
        self.reference = new_reference;
        self.payload = new_payload;
        self.schedule = new_schedule;
        self.action = new_action;
        self.status = if self.schedule.is_some() {
            Status::Scheduled
        } else {
            Status::OnDemand
        };
        // NOTE: we leave last_ran_at as is.
    }
}

#[serde_as]
#[skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TriggerManifest {
    pub id: TriggerId,
    pub project: ValidShardedId<ProjectId>,
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
    pub action: Action,
    pub reference: Option<String>,
    pub schedule: Option<Schedule>,
    pub status: Status,
    pub last_ran_at: Option<DateTime<Utc>>,
}

#[derive(
    Debug,
    Default,
    Clone,
    Serialize,
    Deserialize,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "String(None)")]
pub enum Status {
    #[default]
    #[sea_orm(string_value = "Scheduled")]
    Scheduled,
    #[sea_orm(string_value = "OnDemand")]
    OnDemand,
    #[sea_orm(string_value = "Expired")]
    Expired,
    #[sea_orm(string_value = "Cancelled")]
    Cancelled,
    #[sea_orm(string_value = "Paused")]
    Paused,
}

impl Status {
    // Alive means that it should continue to live in the spinner map. A paused
    // trigger is considered alive, but it won't be rund. We will advance
    // its clock as if it was run though.
    pub fn alive(&self) -> bool {
        [Self::Scheduled, Self::Paused].contains(self)
    }

    pub fn cancelleable(&self) -> bool {
        [Self::Scheduled, Self::Paused, Self::OnDemand].contains(self)
    }

    pub fn as_operation(&self) -> String {
        match self {
            | Status::Scheduled => "resume",
            | Status::Expired => "expire",
            | Status::Cancelled => "cancel",
            | Status::Paused => "pause",
            | _ => "invalid",
        }
        .to_owned()
    }
}

#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult,
)]
#[serde(rename_all = "snake_case")]
#[serde(untagged)]
pub enum Schedule {
    Recurring(Recurring),
    RunAt(RunAt),
}

#[skip_serializing_none]
#[serde_as]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
pub struct RunAt {
    #[serde(with = "iso8601_dateformat_vec_serde")]
    pub timepoints: Vec<DateTime<Tz>>,
    // Ignored if set through the API.
    pub remaining: Option<u64>,
}

#[skip_serializing_none]
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Recurring {
    pub cron: Option<String>,
    pub timezone: String,
    pub limit: Option<u64>,
    pub remaining: Option<u64>,
}

impl Default for Recurring {
    fn default() -> Self {
        Self {
            cron: None,
            timezone: "Etc/UTC".to_owned(),
            limit: None,
            remaining: None,
        }
    }
}

#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult,
)]
//#[serde(rename_all = "snake_case")]
#[serde(untagged)]
pub enum Action {
    Event(Event),
    Webhook(Webhook),
}

#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Event {
    #[serde(rename = "type")]
    pub _kind: MustBe!("event"),
    event: String,
}

#[serde_as]
#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult,
)]
pub struct Payload {
    pub headers: HashMap<String, String>,
    pub content_type: String,
    pub body: String,
}
